ASC-457 Enforce Python Filename Formatting
rcbops/flake8-filename pull request #1
Opened 2018-05-29 19:02 UTC by ryan-rs

Add logic to validate Python filenames using user defined patterns.

2018-05-29 19:57 UTC, johnduarte requested changes

2018-05-29 19:57 UTC, johnduarte commented on docs/release_process.rst
> +5. The task will stop and prompt you for you PyPI username and password if you dont have these set in your `.pypirc` file.
s/dont/don't/

2018-05-29 22:56 UTC, johnduarte approved these changes

2018-05-30 14:30 UTC, zreichert requested changes
Needs some small changes.

2018-05-30 14:30 UTC, zreichert commented on docs/violation_codes.rst
> +| M5XX | filename fails user defined regex pattern                                                        |
Copy pasta! 
Should be `N5XX`

2018-05-30 14:30 UTC, zreichert commented on setup.py
> +    author_email='rcb-deploy@lists.rackspace.com',
Should this be `rpc-automation@rackspace.com`?

2018-05-30 14:31 UTC, zreichert commented
@ryan-rs I see the 1.0.0 release label.  Are you sure you want to start there?

2018-05-30 14:50 UTC, ryan-rs commented
@zreichert Yeah, I'm feeling bullish. I really don't see any future features going into this linting plug-in.

2018-05-30 15:59 UTC, zreichert approved these changes
![money](https://media.giphy.com/media/24FIiwrTB3dYvMfb8E/giphy.gif)

2018-05-30 15:59 UTC, merged